### ISSUE TITLE
Fix local function recursion issue

### ISSUE THREAD

**Issue by d5** [d5/tengo#56]
```golang
// global recursive function: works perfectly
sum_g := func(a) {
    return a == 0 ? 0 : a + sum_g(a-1)
}
print(sum_g(10)) // 55

// local recursive function: causes an error
func() {
    sum := func(a) {
        return a == 0 ? 0 : a + sum(a-1)  // error
    }

    return sum(10)
}()

// workaround
func() {
    sum := undefined
    sum = func(a) {
        return a == 0 ? 0 : a + sum(a-1)  // ok
    }

    return sum(10)
}()
```

[Playground](https://tengolang.com/?s=7a322ffcfdfc898a41cdd7c750aa0aa2695345cc)

```yaml
Instructions:
  0000 CONST   5    
  0003 CALL    0    
  0005 SETG    0    


Constants:
  [0] 0 (int)
  [1] 0 (int)
  [2] 1 (int)
  [3] (function)
    0000 GETL    0    
    0002 CONST   0    
    0005 EQL    
    0006 JMPF    15   
    0009 CONST   1    
    0012 JMP     28   
    0015 GETL    0    
    0017 GETF    0    
    0019 GETL    0    
    0021 CONST   2    
    0024 SUB    
    0025 CALL    1    
    0027 ADD    
    0028 RETVAL  1    
  [4] 10 (int)
  [5] (function)
    0000 GETL    0    
    0002 CLOSURE 3     1    
    0006 DEFL    0    
    0008 GETL    0    
    0010 CONST   4    
    0013 CALL    1    
    0015 RETVAL  1    
```

**Comment by prologic** [comment]
This has not been fixed by the mentioned commits:

```
$ tengo
>> wrapper := func() { inner := func(x) { if (x == 0) { return 0 } else { return inner(x - 1) } }; return inner(1) }
<compiled-function>
>> wrapper()
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/d5/tengo/runtime.(*VM).pushClosure(0xc000080370, 0x3, 0x1, 0x0, 0x0)
	/Users/prologic/Contributions/tengo/runtime/vm.go:1060 +0x34c
github.com/d5/tengo/runtime.(*VM).Run(0xc000080370, 0xc0000ac000, 0x400)
	/Users/prologic/Contributions/tengo/runtime/vm.go:933 +0x58b2
main.runREPL(0x11fc400, 0xc00000c010, 0x11fc420, 0xc00000c018)
	/Users/prologic/Contributions/tengo/cmd/tengo/main.go:218 +0x5ea
main.main()
	/Users/prologic/Contributions/tengo/cmd/tengo/main.go:53 +0x4ff
```

This is on the latest master after a `git pull` and `go install ./...`

**Comment by d5** [comment]
It's probably an issue with REPL code. Same code works fine in playground (https://tengolang.com/?s=e1bf7d1e99b81c312d9b02bdc6735a11daf1d93a). I will take a look. Thanks for reporting!!

**Comment by prologic** [comment]
Ahh I did not test with a full program; only on the REPL. No worries :)

**Comment by d5** [comment]
Found the cause, and, opened #91.
